apiVersion: v1
kind: Service
metadata:
  name: qide-backend-svc
  namespace: topdog-staging
  labels:
    environment: staging
spec:
  selector:
    app: qide-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
