apiVersion: v1
kind: ConfigMap
metadata:
  name: qide-app-config
  namespace: topdog-ide
data:
  FRONTEND_URL: "https://topdog-ide.com"
  BACKEND_URL: "https://api.topdog-ide.com"
  WORKSPACE_PROFILE: "dev"
  ENABLE_HOST_REDIRECT: "true"
  CANONICAL_HOST: "topdog-ide.com"
  ALTERNATE_HOSTS: "www.topdog-ide.com"
