apiVersion: v1
kind: ConfigMap
metadata:
  name: qide-app-config
  namespace: topdog-ide
data:
  FRONTEND_URL: "https://topdog-ide.com"
  BACKEND_URL: "https://topdog-ide.com"
  WORKSPACE_PROFILE: "dev"
