apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qide-ingress
  namespace: topdog-ide
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - topdog-ide.com
      secretName: qide-frontend-tls
    - hosts:
        - api.topdog-ide.com
      secretName: qide-backend-tls
  rules:
    - host: topdog-ide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qide-frontend-svc
                port:
                  number: 80
    - host: api.topdog-ide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qide-backend-svc
                port:
                  number: 8000
