apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: q-ide-redirect
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: https://topdog-ide.com$request_uri
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
spec:
  tls:
    - hosts:
        - q-ide.com
        - www.q-ide.com
      secretName: q-ide-redirect-tls
  rules:
    - host: q-ide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qide-backend-svc
                port:
                  number: 8000
    - host: www.q-ide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qide-backend-svc
                port:
                  number: 8000
