apiVersion: v2
name: topdog
description: Helm chart for deploying Top Dog (Aura) application
home: https://q-ide.com
icon: https://q-ide.com/favicon.ico
type: application
version: 0.1.0
appVersion: "1.0.0"
