apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: topdog-ide
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - topdog-ide.com
        - www.topdog-ide.com
      secretName: topdog-ide-tls
  rules:
    - host: topdog-ide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: topdog-ide-backend
                port:
                  number: 80
    - host: www.topdog-ide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: topdog-ide-backend
                port:
                  number: 80
