apiVersion: v1
kind: Service
metadata:
  name: topdog-ide-backend
  labels:
    app: topdog-ide-backend
spec:
  type: ClusterIP
  selector:
    app: topdog-ide-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
