apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: topdog-tls-final
  namespace: topdog
spec:
  secretName: topdog-tls-final
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - topdog-ide.com
    - www.topdog-ide.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - topdog-ide.com
      - www.topdog-ide.com
