apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "topdog.fullname" . }}
  labels:
    {{- include "topdog.labels" . | nindent 4 }}
data:
  # Example: you can mount static config if needed
  app.yaml: |
    marketplace:
      mode: {{ .Values.env.MARKETPLACE_MODE | quote }}
