apiVersion: v1
kind: Service
metadata:
  name: {{ include "topdog.fullname" . }}-router
  labels:
    {{- include "topdog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    # Router service points at the STABLE release by default
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
